### PR TITLE
Update setup.tra

### PR DESCRIPTION
**Pull request by Felipefpl**
1 - improved my previous translation to brazilian portuguese.

2 - i have a request to make: please rename the folder where my translation is: the Bigg didnt care to write the correct name regarding my translation which i informed years ago, it must be "brazilian portuguese" instead of the "portoguese" he wrote. Portoguese is written wrong aside misleading users making them think it's a translation from Portugal instead of Brazil.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks! Are you done or will you update it further?

**Comment by Felipefpl** [comment]
Nope, everything is fully translated in a good way for me.

**Comment by ALIENQuake** [comment]
@lynxlynxlynx @Felipefpl This PR changes the setup.tra into UTF8 encoding because the edits were made using a web interface. You should either rever it and transfer the changes locally or recode the mod to use UTF8-based HANDLE_CHARSETS. For the second, I can provide PR.

**Comment by lynxlynxlynx** [comment]
That would be helpful, yes. I've had it on my radar, but since I've never done it before, please go ahead. I'm currently cleaning up some other things and docs, will push soon. But it doesn't touch the code yet.

**Comment by Felipefpl** [comment]
> 
> 
> @lynxlynxlynx @Felipefpl This PR changes the setup.tra into UTF8 encoding because the edits were made using a web interface. You should either rever it and transfer the changes locally or recode the mod to use UTF8-based HANDLE_CHARSETS. For the second, I can provide PR.

Thank you very much for chaging/submitting the file for me, i didnt know i needed to make these changes on it. Neither i knew there were translated readmes, it seems i'll have to translate again. :)

**Comment by lynxlynxlynx** [comment]
I'm still updating the readme, so best to wait a bit. Also there's no point in translating the changelog — see how it's done in the other two translations.

**Comment by Felipefpl** [comment]
> I'm still updating the readme, so best to wait a bit. Also there's no point in translating the changelog — see how it's done in the other two translations.

I see, thanks for the info.

**Comment by lynxlynxlynx** [comment]
@ALIENQuake are you sure an update is really needed? It works for me, I guess since the mod doesn't touch dialog.tlk.

**Comment by lynxlynxlynx** [comment]
@Felipefpl: the readme is now final.

**Comment by Felipefpl** [comment]
> @Felipefpl: the readme is now final. I've also changed your S/N translation to Y/N, since only those keys will make the install continue.

I understand, is there an explanation for those who will translate to keep y/n? This'd be good to avoid problems in the future, thanks for changing the files. ;)

**Comment by lynxlynxlynx** [comment]
You can add comments to the file like this:
```
// these
// will be
// ignored
```
But I doubt there'll be further need for translation updates, even if there is a new release in another five year's time.

**Comment by Felipefpl** [comment]
Good to know, thanks for the comments.

**Comment by Felipefpl** [comment]
> @Felipefpl: renamed the folder and translation name. :)

Hi, i believe it's better to rename back to brazilian portuguese since there is no "brazilian" language, specially also because the bigg renamed my language file to something it was not correct too.

**Comment by lynxlynxlynx** [comment]
I don't know if weidu can handle spaces in names or that long names, as it has to match somewhere else. All the docs properly use brazilian portuguese too. My first idea was to just use pt_BR, btw.

**Comment by ALIENQuake** [comment]
pt_BR +1

**Comment by Felipefpl** [comment]
> I don't know if weidu can handle spaces in names or that long names, as it has to match somewhere else. All the docs properly use brazilian portuguese too. My first idea was to just use pt_BR, btw.

I'll make an issue for this at weidu then, small names just wont do.

**Comment by lynxlynxlynx** [comment]
But have you checked it actually doesn't work?

**Pull request merged**
